import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/fonts/fonts.css";

import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../theme/theme";
import ClientNavbar from "./Navbar/ClientNavbar";
import Footer from './Footer/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vansaya Product Experience | Review",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientNavbar />
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
